---
- name: Install 389DS with zypper
  community.general.zypper:
    name: "{{ dirsrv_product }}"
    state: present
    update_cache: no

- name: Get package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check 389DS package version
  ansible.builtin.set_fact:
    dirsrv_package_version: "{{ ansible_facts.packages[dirsrv_product][0].version }}"
