---
- name: Converge
  hosts: all

  vars:
    dirsrv_rootdn_password: "P455W0RD"
    dirsrv_listen_host: 0.0.0.0

    dirsrv_tls_enabled: true
    dirsrv_tls_enforced: true
    dirsrv_tls_files_remote: false
    dirsrv_tls_certificate_trusted: false

    dirsrv_tls_cert_file: tls_test_local_cert.pem
    dirsrv_tls_key_file: tls_test_local.key

    dirsrv_create_suffix_entry: True
  pre_tasks:
    # The following two tasks when executed together are always idempotent (as they replace the same file with the same content) but they register as changed
    # from Ansible's perspective. Since there is no easy way to determine wether the existing file is the original binary or the replacement script (checksum
    # matching is not possible as both the systemctl binary and the replacement script might be updated at any time in the future) then the only option is to
    # force the two tasks to not change.
    - name: Remove systemctl binary
      become: true
      file:
        path: /usr/bin/systemctl
        state: absent
      changed_when: false
      when: ansible_facts["nodename"] is search("SYSCTL")

    # The test suite uses the "docker systemctl replacement" script created and distributed by gdraheim under the EUPL license. The script gets downloaded and
    # copied to a local container to allow for the tests to execute correctly. Such distribution happens under the same license and terms upon which gdraheim
    # created and published their work. The script is downloaded as-is and no alteration to it is made whatsoever. By running the tests on their machines the
    # end users agrees to handle the downloaded script under the terms of the EUPL as intended by its author. Note that this task, and the role overall is
    # still licensed under the Apache 2 license as opposed as the downloaded asset which is licensed under the EUPL.
    - name: Implant systemctl replacement
      become: true
      uri:
        creates: /usr/local/bin/systemctl
        dest: /usr/bin/systemctl
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
        url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/1bb5768abbf68245b7b6a8bd9d6ac4df4d78044f/files/docker/systemctl.py
      changed_when: false
      when: ansible_facts["nodename"] is search("SYSCTL")

    - name: Create dirsrv service dropin directory
      file:
        path: /etc/systemd/system/dirsrv@.service.d/
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
        state: directory

    - name: Copy dirsrv service dropin config
      become: true
      copy:
        src: dirsrv-dropin.conf
        dest: /etc/systemd/system/dirsrv@.service.d/custom.conf
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
        force: true

    # Ansible is not secure enough for a SSF of 256 for 389DS 1.4.X
    # Unfortunately we don't yet have access to dirsrv_legacy or the installed version so we need to base the condition on the CentOS version
    - name: Set minimum SSF
      set_fact:
        dirsrv_tls_minssf: "{%if ansible_facts['distribution_major_version'] | int == 8 %}128{% else %}256{% endif %}"

  roles:
    - role: lvps.389ds_server

  tasks:
    - name: Ensure we can access the server, for testing
      ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=config"
        objectClass: "top"
        start_tls: "{{ dirsrv_tls_enabled }}"
        validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
        state: present

    - block:
        - name: Ensure TLS is enforced
          ldap_entry:
            server_uri: "ldap://localhost"
            bind_dn: "{{ dirsrv_rootdn }}"
            bind_pw: "{{ dirsrv_rootdn_password }}"
            dn: "{{ dirsrv_suffix }}"
            objectClass: "domain"
            start_tls: "false"
            state: present
          register: dirsrv_tls_test

      rescue:
        - name: Assert that task failed successfully
          assert:
            that:
              - "{{ dirsrv_tls_test.details }}.info == 'Minimum SSF not met.'"
