# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y {{ item.python_package }} sudo bash ca-certificates iproute && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install {{ item.python_package }} sudo {{ item.python_devel_package }} python*-dnf bash iproute {% if item.install_epel %}epel-release{% endif %} && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y {{ item.python_package }} sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y {{ item.python_package }} sudo bash python-xml iproute && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache {{ item.python_package }} sudo bash iproute ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y {{ item.python_package }} sudo bash ca-certificates iproute && xbps-remove -O; fi
